name: random_color_generator
description: "An app that generates random colors"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.1
  intl: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  solid_lints: ^0.3.3

flutter:
  generate: true
  uses-material-design: true
